# Cấu hình cổng server
server.port=8081
spring.application.name=auth-service

# Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobradar_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# ===============================
# JWT (JSON Web Token) Config
# ===============================
# Lấy từ biến môi trường JWT_SECRET_KEY, nếu không có (chạy ở máy Dev) thì dùng chuỗi mặc định phía sau dấu ':'
application.security.jwt.secret-key=${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# Tương tự với thời gian sống của token
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}