/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#bacffe",
        "background": "#020617",
        "tertiary": "#94a3b8",
        "on-error": "#ffffff",
        "primary": "#0052ff",
        "inverse-primary": "#b7c4ff",
        "tertiary-fixed-dim": "#bfc6dd",
        "tertiary-fixed": "#dbe2fa",
        "surface-bright": "#1e293b",
        "primary-fixed-dim": "#b7c4ff",
        "on-primary-container": "#dfe3ff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#0038b6",
        "surface-dim": "#010409",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#141b2c",
        "on-primary-fixed": "#001452",
        "outline-variant": "rgba(255, 255, 255, 0.1)",
        "secondary-fixed": "#d8e2ff",
        "on-background": "#f8fafc",
        "surface": "#020617",
        "on-tertiary-fixed-variant": "#3f4759",
        "secondary-fixed-dim": "#b2c7f6",
        "tertiary-container": "#1e293b",
        "on-surface": "#f8fafc",
        "inverse-on-surface": "#0b1c30",
        "surface-container-highest": "#1e293b",
        "primary-fixed": "#dde1ff",
        "inverse-surface": "#f8fafc",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#32466e",
        "surface-container-low": "rgba(15, 23, 42, 0.6)",
        "secondary-container": "#1e293b",
        "on-error-container": "#93000a",
        "on-surface-variant": "#94a3b8",
        "surface-tint": "#0052ff",
        "on-tertiary-container": "#dde4fc",
        "surface-container-lowest": "#020617",
        "outline": "#475569",
        "surface-container": "#0f172a",
        "primary-container": "#0052ff",
        "surface-variant": "#1e293b",
        "surface-container-high": "#0f172a",
        "secondary": "#64748b",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#001a40"
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "24px",
        "container-max": "1440px",
        "base": "8px",
        "gutter": "32px"
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "display-lg": ["56px", {"lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "800"}],
        "headline-md": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    }
  },
  plugins: [],
}
