# Cấu hình cổng chạy cho Crawler Service
server.port=8084
spring.application.name=crawler-service

# Đường dẫn URL gọi trực tiếp sang Job Service
services.job-service.url=http://localhost:8083

# Đường dẫn URL tới dịch vụ FlareSolverr vượt Cloudflare
services.flaresolverr.url=http://localhost:8191/v1
