# Cấu hình cổng chạy cho Job Service
server.port=8083
spring.application.name=job-service

# Cấu hình kết nối PostgreSQL (Dành riêng cho job-service)
spring.datasource.url=jdbc:postgresql://localhost:5432/jobradar_job_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Cấu hình Redis Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Cấu hình thời gian sống mặc định cho Cache (ví dụ 10 phút = 600000 ms)
spring.cache.redis.time-to-live=600000
spring.cache.type=redis
