# Cấu hình cổng chạy cho Job Service
server.port=8083
spring.application.name=job-service

# Cấu hình kết nối PostgreSQL (Dành riêng cho job-service)
spring.datasource.url=jdbc:postgresql://localhost:5432/jobradar_job_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
